# Generated by Django 5.1.15 on 2026-06-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_backfill_fcsky'),
        ('notices', '0002_notice_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='clubs.club', verbose_name='클럽'),
        ),
    ]
