# Generated by Django 5.1.15 on 2026-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: 우승, 준우승, 득점왕', max_length=120, verbose_name='수상명')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='순위')),
                ('date_awarded', models.DateField(blank=True, null=True, verbose_name='수상일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '입상 내역',
                'verbose_name_plural': '입상 내역',
                'ordering': ['-date_awarded', '-season__year'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='대회명')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 슬러그')),
                ('kind', models.CharField(choices=[('LEAGUE', '리그'), ('TOURNAMENT', '토너먼트'), ('CUP', '컵 대회')], max_length=12, verbose_name='종류')),
                ('organizer', models.CharField(blank=True, max_length=120, verbose_name='주최')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '대회',
                'verbose_name_plural': '대회',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
            ],
            options={
                'verbose_name': '대회 출전',
                'verbose_name_plural': '대회 출전',
                'ordering': ['-season__year', 'competition'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 2026', max_length=50, verbose_name='시즌명')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 시즌')),
            ],
            options={
                'verbose_name': '시즌',
                'verbose_name_plural': '시즌',
                'ordering': ['-year'],
            },
        ),
    ]
