# Generated by Django 5.1.15 on 2026-06-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='teams.player', verbose_name='선수'),
        ),
        migrations.AddField(
            model_name='award',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='teams.team', verbose_name='팀'),
        ),
        migrations.AddField(
            model_name='award',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='competitions.competition', verbose_name='대회'),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition', verbose_name='대회'),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='teams.team', verbose_name='팀'),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.season', verbose_name='시즌'),
        ),
        migrations.AddField(
            model_name='award',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='competitions.season', verbose_name='시즌'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together={('team', 'competition', 'season')},
        ),
    ]
