# Generated by Django 5.1.15 on 2026-06-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
        ('teams', '0003_player_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-year', 'name'], 'verbose_name': '대회', 'verbose_name_plural': '대회'},
        ),
        migrations.AlterModelOptions(
            name='competitionentry',
            options={'ordering': ['-competition__year', 'competition'], 'verbose_name': '대회 출전', 'verbose_name_plural': '대회 출전'},
        ),
        migrations.AddField(
            model_name='competition',
            name='year',
            field=models.PositiveIntegerField(default=2026, verbose_name='연도'),
        ),
        migrations.AlterField(
            model_name='competitionentry',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.season', verbose_name='시즌'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('2030', '20-30대'), ('40', '40대'), ('50', '50대'), ('OPEN', '오픈')], max_length=8, verbose_name='연령 부문')),
                ('name', models.CharField(blank=True, help_text='비우면 연령 부문 표시명을 사용(예: 40대부문).', max_length=60, verbose_name='부문명')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='competitions.competition', verbose_name='대회')),
            ],
            options={
                'verbose_name': '부문',
                'verbose_name_plural': '부문',
                'ordering': ['competition', 'age_group'],
                'unique_together': {('competition', 'age_group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='competitions.division', verbose_name='부문'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together={('team', 'competition', 'division')},
        ),
    ]
