# Generated by Django 5.1.15 on 2026-06-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_backfill_divisions'),
        ('matches', '0008_remove_match_season_remove_opponentmatch_season'),
        ('teams', '0005_remove_teammembership_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionentry',
            name='season',
        ),
        migrations.RemoveField(
            model_name='award',
            name='season',
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-date_awarded', '-competition__year'], 'verbose_name': '입상 내역', 'verbose_name_plural': '입상 내역'},
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
