# Generated by Django 5.1.15 on 2026-06-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_award_club'),
        ('matches', '0012_match_club_opponent_club_opponentmatch_club_and_more'),
        ('teams', '0006_player_club_team_club_alter_team_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionentry',
            options={'ordering': ['-competition__year', 'competition'], 'verbose_name': '대회 참가팀', 'verbose_name_plural': '대회 참가팀'},
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='competitionentry',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='matches.opponent', verbose_name='외부팀'),
        ),
        migrations.AlterField(
            model_name='competitionentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='teams.team', verbose_name='우리 팀'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionentry',
            unique_together={('competition', 'division', 'opponent'), ('competition', 'division', 'team')},
        ),
    ]
