# Generated by Django 5.1.15 on 2026-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_award_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='half_length_minutes',
            field=models.PositiveIntegerField(default=45, verbose_name='전후반 길이(분)'),
        ),
        migrations.AddField(
            model_name='division',
            name='half_length_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='비우면 대회 기본값 사용.', null=True, verbose_name='전후반 길이(분)'),
        ),
    ]
