# Generated by Django 5.1.15 on 2026-06-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_competition_half_length_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='extra_half_minutes',
            field=models.PositiveIntegerField(default=15, verbose_name='연장 길이(분)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='extra_time_single',
            field=models.BooleanField(default=False, help_text='체크하면 연장을 전·후반 없이 한 번에 진행(휴식 없음).', verbose_name='연장 단일 진행'),
        ),
        migrations.AddField(
            model_name='division',
            name='extra_half_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='비우면 대회 기본값 사용.', null=True, verbose_name='연장 길이(분)'),
        ),
        migrations.AddField(
            model_name='division',
            name='extra_time_single',
            field=models.BooleanField(blank=True, help_text='비우면 대회 기본값 사용.', null=True, verbose_name='연장 단일 진행'),
        ),
    ]
