# Generated by Django 5.1.15 on 2026-06-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='gallery/%Y/%m/', verbose_name='사진')),
                ('video_url', models.URLField(blank=True, help_text='YouTube 등 외부 영상', verbose_name='영상 링크')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='설명')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='촬영/행사일')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '갤러리',
                'verbose_name_plural': '갤러리',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
