# Generated by Django 5.1.15 on 2026-06-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='출생 연도')),
                ('position', models.CharField(blank=True, choices=[('GK', '골키퍼'), ('DF', '수비수'), ('MF', '미드필더'), ('FW', '공격수')], max_length=2, verbose_name='주 포지션')),
                ('photo', models.ImageField(blank=True, upload_to='players/', verbose_name='사진')),
                ('bio', models.TextField(blank=True, verbose_name='프로필')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '선수',
                'verbose_name_plural': '선수',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='팀 이름')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 슬러그')),
                ('age_group', models.CharField(choices=[('K7', 'K7 (20-30대)'), ('40', '40대'), ('50', '50대')], max_length=4, verbose_name='연령대')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='창단일')),
                ('logo', models.ImageField(blank=True, upload_to='teams/logos/', verbose_name='로고')),
                ('description', models.TextField(blank=True, verbose_name='소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '팀',
                'verbose_name_plural': '팀',
                'ordering': ['age_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='등번호')),
                ('is_captain', models.BooleanField(default=False, verbose_name='주장')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='합류일')),
                ('left_date', models.DateField(blank=True, null=True, verbose_name='탈퇴일')),
                ('is_active', models.BooleanField(default=True, verbose_name='현재 활동')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.player', verbose_name='선수')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.season', verbose_name='시즌')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team', verbose_name='팀')),
            ],
            options={
                'verbose_name': '팀 소속',
                'verbose_name_plural': '팀 소속',
                'ordering': ['team', 'jersey_number'],
                'unique_together': {('player', 'team', 'season')},
            },
        ),
    ]
