# Generated by Django 5.1.15 on 2026-06-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='squad',
            field=models.CharField(blank=True, help_text='대회 구분용 임시 필드 (예: 50대초, 50대말). 추후 대회별·팀별 로스터 모델로 분리 예정.', max_length=20, verbose_name='구분(임시)'),
        ),
    ]
