# Generated by Django 5.1.15 on 2026-06-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_options_and_more'),
        ('teams', '0003_player_deleted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competitions.competition', verbose_name='대회'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='competitions.division', verbose_name='부문'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('player', 'team', 'competition')},
        ),
    ]
