# Generated by Django 5.1.15 on 2026-06-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_teammembership_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='season',
        ),
    ]
