# Generated by Django 5.1.15 on 2026-06-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_backfill_fcsky'),
        ('teams', '0006_player_club_team_club_alter_team_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='clubs.club', verbose_name='클럽'),
        ),
    ]
