# Generated by Django 5.1.15 on 2026-06-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='팀명')),
                ('short_name', models.CharField(blank=True, max_length=40, verbose_name='약칭')),
                ('logo', models.ImageField(blank=True, upload_to='opponents/logos/', verbose_name='로고')),
            ],
            options={
                'verbose_name': '상대팀',
                'verbose_name_plural': '상대팀',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home', models.BooleanField(default=True, verbose_name='홈 경기')),
                ('kickoff', models.DateTimeField(verbose_name='경기 일시')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='장소')),
                ('status', models.CharField(choices=[('SCHEDULED', '예정'), ('LIVE', '진행 중'), ('FINISHED', '종료'), ('POSTPONED', '연기'), ('CANCELLED', '취소')], default='SCHEDULED', max_length=12, verbose_name='상태')),
                ('our_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='우리 득점')),
                ('opponent_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='상대 득점')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.competition', verbose_name='대회')),
                ('our_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.team', verbose_name='우리 팀')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='competitions.season', verbose_name='시즌')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.opponent', verbose_name='상대팀')),
            ],
            options={
                'verbose_name': '경기',
                'verbose_name_plural': '경기',
                'ordering': ['-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('OUR', '우리 팀'), ('OPPONENT', '상대팀')], default='OUR', max_length=8, verbose_name='팀 구분')),
                ('event_type', models.CharField(choices=[('GOAL', '득점'), ('ASSIST', '도움'), ('OWN_GOAL', '자책골'), ('YELLOW', '경고'), ('RED', '퇴장'), ('SUB_IN', '교체 IN'), ('SUB_OUT', '교체 OUT')], max_length=10, verbose_name='이벤트')),
                ('minute', models.PositiveIntegerField(blank=True, null=True, verbose_name='분')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match', verbose_name='경기')),
                ('player', models.ForeignKey(blank=True, help_text='우리 팀 이벤트일 때 선택', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_events', to='teams.player', verbose_name='선수')),
            ],
            options={
                'verbose_name': '경기 이벤트',
                'verbose_name_plural': '경기 이벤트',
                'ordering': ['match', 'minute', 'id'],
            },
        ),
    ]
