# Generated by Django 5.1.15 on 2026-06-15 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpponentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('K7', 'K7 (20-30대)'), ('40', '40대'), ('50', '50대')], help_text='어느 부문(조)의 경기인지', max_length=4, verbose_name='부문')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='홈 득점')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='원정 득점')),
                ('kickoff', models.DateTimeField(blank=True, null=True, verbose_name='경기 일시')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_opponent_matches', to='matches.opponent', verbose_name='원정팀')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_matches', to='competitions.competition', verbose_name='대회')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_opponent_matches', to='matches.opponent', verbose_name='홈팀')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opponent_matches', to='competitions.season', verbose_name='시즌')),
            ],
            options={
                'verbose_name': '상대팀 간 경기',
                'verbose_name_plural': '상대팀 간 경기',
                'ordering': ['competition', 'age_group', 'id'],
            },
        ),
    ]
