# Generated by Django 5.1.15 on 2026-06-16 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchevent_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='유튜브 영상 URL (watch/youtu.be/shorts/embed 모두 가능)', max_length=300, verbose_name='유튜브 링크')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='matches.match', verbose_name='경기')),
            ],
            options={
                'verbose_name': '경기 영상',
                'verbose_name_plural': '경기 영상',
                'ordering': ['id'],
            },
        ),
    ]
