# Generated by Django 5.1.15 on 2026-06-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchvideo'),
        ('teams', '0002_player_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STARTER', '선발'), ('BENCH', '벤치')], default='STARTER', max_length=8, verbose_name='역할')),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='등번호')),
                ('is_captain', models.BooleanField(default=False, verbose_name='주장')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='matches.match', verbose_name='경기')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='teams.player', verbose_name='선수')),
            ],
            options={
                'verbose_name': '출전 명단',
                'verbose_name_plural': '출전 명단',
                'ordering': ['match', 'role', 'jersey_number', 'player__name'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
