# Generated by Django 5.1.15 on 2026-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchlineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='중계 시작 시각'),
        ),
    ]
