# Generated by Django 5.1.15 on 2026-06-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_options_and_more'),
        ('matches', '0006_match_live_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competitions.division', verbose_name='부문'),
        ),
    ]
