# Generated by Django 5.1.15 on 2026-06-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='opponentmatch',
            name='season',
        ),
    ]
