# Generated by Django 5.1.15 on 2026-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_match_season_remove_opponentmatch_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('GROUP', '조별리그'), ('RO16', '16강'), ('QF', '8강'), ('SF', '준결승'), ('3RD', '3·4위전'), ('F', '결승')], default='GROUP', help_text='조별리그 / 녹아웃(8강·준결승·결승 등)', max_length=6, verbose_name='단계'),
        ),
    ]
