# Generated by Django 5.1.15 on 2026-06-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_backfill_stage_from_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='advance_feeder',
            field=models.ForeignKey(blank=True, help_text='우리가 선택한 경기(예: 우리 준결승)에서 이겨야 이 경기에 진출.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_to', to='matches.match', verbose_name='우리 진출 경기'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_feeder',
            field=models.ForeignKey(blank=True, help_text='이 경기의 상대 = 선택한 경기의 승자(예: 반대편 준결승).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_opponent_of', to='matches.opponentmatch', verbose_name='상대 진출 경기'),
        ),
        migrations.AddField(
            model_name='opponentmatch',
            name='stage',
            field=models.CharField(choices=[('GROUP', '조별리그'), ('RO16', '16강'), ('QF', '8강'), ('SF', '준결승'), ('3RD', '3·4위전'), ('F', '결승')], default='GROUP', help_text='조별리그 / 녹아웃(반대편 준결승 등)', max_length=6, verbose_name='단계'),
        ),
    ]
