# Generated by Django 5.1.15 on 2026-06-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_backfill_fcsky'),
        ('matches', '0013_alter_match_opponent_feeder_alter_opponent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='clubs.club', verbose_name='클럽'),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_feeder',
            field=models.ForeignKey(blank=True, help_text='이 경기의 상대(away_entry) = 선택한 경기의 승자(예: 반대편 준결승).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_opponent_of', to='matches.match', verbose_name='상대 진출 경기'),
        ),
    ]
