# Generated by Django 5.1.15 on 2026-06-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_alter_match_club_alter_match_opponent_feeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='period',
            field=models.CharField(choices=[('SCHEDULED', '시작 전'), ('FIRST', '전반'), ('HALFTIME', '하프타임'), ('SECOND', '후반'), ('FINISHED', '종료')], default='SCHEDULED', max_length=12, verbose_name='진행 단계'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_half_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='후반 시작 시각'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='half',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='전/후반'),
        ),
        migrations.AlterField(
            model_name='match',
            name='live_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='전반 시작 시각'),
        ),
    ]
