# Generated by Django 5.1.15 on 2026-06-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_match_paused_at_match_paused_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_pso_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='원정 승부차기'),
        ),
        migrations.AddField(
            model_name='match',
            name='et_first_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='연장 전반 시작 시각'),
        ),
        migrations.AddField(
            model_name='match',
            name='et_second_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='연장 후반 시작 시각'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_pso_score',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='홈 승부차기'),
        ),
        migrations.AlterField(
            model_name='match',
            name='period',
            field=models.CharField(choices=[('SCHEDULED', '시작 전'), ('FIRST', '전반'), ('HALFTIME', '하프타임'), ('SECOND', '후반'), ('ET_FIRST', '연장 전반'), ('ET_HALFTIME', '연장 휴식'), ('ET_SECOND', '연장 후반'), ('PENALTIES', '승부차기'), ('FINISHED', '종료')], default='SCHEDULED', max_length=12, verbose_name='진행 단계'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('GOAL', '득점'), ('ASSIST', '도움'), ('OWN_GOAL', '자책골'), ('YELLOW', '경고'), ('RED', '퇴장'), ('SUB_IN', '교체 IN'), ('SUB_OUT', '교체 OUT'), ('PSO_GOAL', '승부차기 성공'), ('PSO_MISS', '승부차기 실패')], max_length=10, verbose_name='이벤트'),
        ),
    ]
