# Generated by Django 5.1.15 on 2026-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_match_away_pso_score_match_et_first_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='went_to_extra_time',
            field=models.BooleanField(default=False, verbose_name='연장전 진행'),
        ),
    ]
