# Generated by Django 5.1.15 on 2026-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_match_went_to_extra_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='side',
            field=models.CharField(choices=[('HOME', '홈'), ('AWAY', '원정')], default='HOME', max_length=8, verbose_name='팀 구분'),
        ),
    ]
